### ISSUE TITLE
issue when trying to delete resources

### ISSUE THREAD

**Issue by abikouo** [ansible-collections/pravic#14]
##### SUMMARY

When trying to delete resources using `resources` module, it appears that the corresponding function is never called for any of the resource

definition
```
resources:
    vnet_1:
      provider: Microsoft.Network
      type: virtualNetworks
      name: test-vnet
      api-version: "2022-07-01"
      resourceGroupName: "{{ resource_group }}"
      parameters:
        properties:
          addressSpace:
            addressPrefixes:
              - 10.0.0.0/16
          flowTimeoutInMinutes: 10
        location: eastus
    subnet_1:
      provider: Microsoft.Network
      type: virtualNetworks
      name: resource:vnet_1.name
      subresource:
        - type: subnets
          name: test-subnet-01
      resourceGroupName: "{{ resource_group }}"
      api-version: "2022-07-01"
      parameters:
        properties:
          addressPrefix: 10.0.0.0/24
```

##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE

```yaml
- cloud.pravic.resources:
      state: absent
      resources: "{{ resources }}"
```

##### EXPECTED RESULTS

Resources should be deleted

##### ACTUAL RESULTS

```paste below
ok: [localhost] => {"changed": false, "resources": {"changed": false}}
```
